//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_ParaBirimleri
    {
        public DilOkulu_ParaBirimleri()
        {
            this.DilOkulu_Ulkeler = new HashSet<DilOkulu_Ulkeler>();
        }
    
        public int Id { get; set; }
        public string Birim { get; set; }
        public int Oncelik { get; set; }
        public byte Durumu { get; set; }
    
        public virtual ICollection<DilOkulu_Ulkeler> DilOkulu_Ulkeler { get; set; }
    }
}
