//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KonaklamaTipiPromosyonTanimlari
    {
        public int Id { get; set; }
        public int KonaklamaTipiId { get; set; }
        public byte PromosyonModelId { get; set; }
        public Nullable<int> ExtraHafta_MinimumHafta { get; set; }
        public Nullable<int> ExtraHafta_UcretsizHaftaSayisi { get; set; }
        public Nullable<int> IndirimPromosyonu_Hafta { get; set; }
        public Nullable<int> IndirimPromosyonu_Oran { get; set; }
        public Nullable<int> KonaklamaBazli_Hafta { get; set; }
        public Nullable<int> KonaklamaBazli_Fiyat { get; set; }
        public Nullable<System.DateTime> PromosyonBitisTarihi { get; set; }
        public Nullable<System.DateTime> KalisTarihiBaslangic { get; set; }
        public Nullable<System.DateTime> KalisTarihiBitis { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_KonaklamaTipleri DilOkulu_KonaklamaTipleri { get; set; }
    }
}
