//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KursTipiFiyatlandirmalari
    {
        public int Id { get; set; }
        public int KursTipiId { get; set; }
        public byte FiyatlandirmaModelId { get; set; }
        public Nullable<int> StandartHafta_HaftaSayisi { get; set; }
        public Nullable<int> HerHaftayaOzel_Hafta { get; set; }
        public Nullable<int> HaftaBazliBirimFiyatli_HaftaBaslangic { get; set; }
        public Nullable<int> HaftaBazliBirimFiyatli_HaftaBitis { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_KursTipleri DilOkulu_KursTipleri { get; set; }
    }
}
