//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Makaleler
    {
        public int Id { get; set; }
        public int YazarId { get; set; }
        public int KategoriId { get; set; }
        public string Baslik { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public string Ozet { get; set; }
        public string Icerik { get; set; }
        public string ResimUrl { get; set; }
        public string Url { get; set; }
        public string ResimThumbUrl { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_Yazarlar DilOkulu_Yazarlar { get; set; }
    }
}
