//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KursTipleri
    {
        public DilOkulu_KursTipleri()
        {
            this.DilOkulu_KursTipiEkUcretleri = new HashSet<DilOkulu_KursTipiEkUcretleri>();
            this.DilOkulu_KursTipiFiyatlandirmalari = new HashSet<DilOkulu_KursTipiFiyatlandirmalari>();
            this.DilOkulu_KursTipiPromosyonTanimlari = new HashSet<DilOkulu_KursTipiPromosyonTanimlari>();
        }
    
        public int Id { get; set; }
        public int OkulId { get; set; }
        public int KursKategoriId { get; set; }
        public string Baslik { get; set; }
        public Nullable<bool> BasTarihiHerPazartesi { get; set; }
        public Nullable<bool> BasTarihiOzel { get; set; }
        public string OzelTarihListesi { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_KursKategorileri DilOkulu_KursKategorileri { get; set; }
        public virtual ICollection<DilOkulu_KursTipiEkUcretleri> DilOkulu_KursTipiEkUcretleri { get; set; }
        public virtual ICollection<DilOkulu_KursTipiFiyatlandirmalari> DilOkulu_KursTipiFiyatlandirmalari { get; set; }
        public virtual ICollection<DilOkulu_KursTipiPromosyonTanimlari> DilOkulu_KursTipiPromosyonTanimlari { get; set; }
        public virtual DilOkulu_Okullar DilOkulu_Okullar { get; set; }
    }
}
