//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KursTipiEkUcretleri
    {
        public int Id { get; set; }
        public int KursTipId { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BititisTarihi { get; set; }
        public decimal Fiyat { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_KursTipleri DilOkulu_KursTipleri { get; set; }
    }
}
