//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Subeler
    {
        public DilOkulu_Subeler()
        {
            this.DilOkulu_SubeSayfalar = new HashSet<DilOkulu_SubeSayfalar>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Telefon { get; set; }
        public string Fax { get; set; }
        public string Adres { get; set; }
        public string EPosta { get; set; }
        public string Icerik { get; set; }
        public string KrokiLink { get; set; }
        public string Url { get; set; }
        public Nullable<int> Oncelik { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual ICollection<DilOkulu_SubeSayfalar> DilOkulu_SubeSayfalar { get; set; }
    }
}
