//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KonaklamaTipleri
    {
        public DilOkulu_KonaklamaTipleri()
        {
            this.DilOkulu_KonaklamaTipiEkUcretleri = new HashSet<DilOkulu_KonaklamaTipiEkUcretleri>();
            this.DilOkulu_KonaklamaTipiFiyatlandirmalari = new HashSet<DilOkulu_KonaklamaTipiFiyatlandirmalari>();
            this.DilOkulu_KonaklamaTipiPromosyonTanimlari = new HashSet<DilOkulu_KonaklamaTipiPromosyonTanimlari>();
        }
    
        public int Id { get; set; }
        public int OkulId { get; set; }
        public int KonaklamaKategoriId { get; set; }
        public string Baslik { get; set; }
        public Nullable<bool> BasTarihiYilBoyu { get; set; }
        public Nullable<bool> BasTarihiOzel { get; set; }
        public string OzelTarihListesi { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_KonaklamaKategorileri DilOkulu_KonaklamaKategorileri { get; set; }
        public virtual ICollection<DilOkulu_KonaklamaTipiEkUcretleri> DilOkulu_KonaklamaTipiEkUcretleri { get; set; }
        public virtual ICollection<DilOkulu_KonaklamaTipiFiyatlandirmalari> DilOkulu_KonaklamaTipiFiyatlandirmalari { get; set; }
        public virtual ICollection<DilOkulu_KonaklamaTipiPromosyonTanimlari> DilOkulu_KonaklamaTipiPromosyonTanimlari { get; set; }
        public virtual DilOkulu_Okullar DilOkulu_Okullar { get; set; }
    }
}
