//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KonaklamaTipiEkUcretleri
    {
        public int Id { get; set; }
        public int KonaklamaTipId { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BititisTarihi { get; set; }
        public decimal Fiyat { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
        public Nullable<int> MaksimumHafta { get; set; }
    
        public virtual DilOkulu_KonaklamaTipleri DilOkulu_KonaklamaTipleri { get; set; }
    }
}
