//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DilOkuluEntities : DbContext
    {
        public DilOkuluEntities()
            : base("name=DilOkuluEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DilOkulu_Kullanicilar> DilOkulu_Kullanicilar { get; set; }
        public DbSet<DilOkulu_Makaleler> DilOkulu_Makaleler { get; set; }
        public DbSet<DilOkulu_Yazarlar> DilOkulu_Yazarlar { get; set; }
        public DbSet<DilOkulu_Haberler> DilOkulu_Haberler { get; set; }
        public DbSet<DilOkulu_Slider> DilOkulu_Slider { get; set; }
        public DbSet<DilOkulu_VizeRehberi> DilOkulu_VizeRehberi { get; set; }
        public DbSet<DilOkulu_GaleriDosyalari> DilOkulu_GaleriDosyalari { get; set; }
        public DbSet<DilOkulu_Galeriler> DilOkulu_Galeriler { get; set; }
        public DbSet<DilOkulu_EtiketIliskileri> DilOkulu_EtiketIliskileri { get; set; }
        public DbSet<DilOkulu_Etiketler> DilOkulu_Etiketler { get; set; }
        public DbSet<DilOkulu_StatikSayfalar> DilOkulu_StatikSayfalar { get; set; }
        public DbSet<DilOkulu_Diller> DilOkulu_Diller { get; set; }
        public DbSet<DilOkulu_Merkez> DilOkulu_Merkez { get; set; }
        public DbSet<DilOkulu_Sehirler> DilOkulu_Sehirler { get; set; }
        public DbSet<DilOkulu_StatikLinkler> DilOkulu_StatikLinkler { get; set; }
        public DbSet<DilOkulu_SunulanProgramlar> DilOkulu_SunulanProgramlar { get; set; }
        public DbSet<DilOkulu_Subeler> DilOkulu_Subeler { get; set; }
        public DbSet<DilOkulu_SubeSayfalar> DilOkulu_SubeSayfalar { get; set; }
        public DbSet<DilOkulu_ParaBirimleri> DilOkulu_ParaBirimleri { get; set; }
        public DbSet<DilOkulu_Ulkeler> DilOkulu_Ulkeler { get; set; }
        public DbSet<DilOkulu_KonaklamaKategorileri> DilOkulu_KonaklamaKategorileri { get; set; }
        public DbSet<DilOkulu_KursTipleri> DilOkulu_KursTipleri { get; set; }
        public DbSet<DilOkulu_KursTipiFiyatlandirmalari> DilOkulu_KursTipiFiyatlandirmalari { get; set; }
        public DbSet<DilOkulu_KursTipiPromosyonTanimlari> DilOkulu_KursTipiPromosyonTanimlari { get; set; }
        public DbSet<DilOkulu_KonaklamaTipiFiyatlandirmalari> DilOkulu_KonaklamaTipiFiyatlandirmalari { get; set; }
        public DbSet<DilOkulu_KonaklamaTipiPromosyonTanimlari> DilOkulu_KonaklamaTipiPromosyonTanimlari { get; set; }
        public DbSet<DilOkulu_KonaklamaTipleri> DilOkulu_KonaklamaTipleri { get; set; }
        public DbSet<DilOkulu_Okullar> DilOkulu_Okullar { get; set; }
        public DbSet<DilOkulu_KonaklamaTipiEkUcretleri> DilOkulu_KonaklamaTipiEkUcretleri { get; set; }
        public DbSet<DilOkulu_KursTipiEkUcretleri> DilOkulu_KursTipiEkUcretleri { get; set; }
        public DbSet<DilOkulu_KursKategorileri> DilOkulu_KursKategorileri { get; set; }
        public DbSet<DilOkulu_KursTipiKargoHaricler> DilOkulu_KursTipiKargoHaricler { get; set; }
    }
}
