//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Yazarlar
    {
        public DilOkulu_Yazarlar()
        {
            this.DilOkulu_Makaleler = new HashSet<DilOkulu_Makaleler>();
        }
    
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string YazarTipi { get; set; }
        public string Aciklama { get; set; }
        public string ResimUrl { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
        public string Pozisyon { get; set; }
        public string Telefon { get; set; }
        public string EPosta { get; set; }
    
        public virtual ICollection<DilOkulu_Makaleler> DilOkulu_Makaleler { get; set; }
    }
}
