//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Sehirler
    {
        public DilOkulu_Sehirler()
        {
            this.DilOkulu_Okullar = new HashSet<DilOkulu_Okullar>();
        }
    
        public int Id { get; set; }
        public int UlkeId { get; set; }
        public string Baslik { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public byte Oncelik { get; set; }
        public string Url { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
        public string SehirProfili { get; set; }
    
        public virtual DilOkulu_Ulkeler DilOkulu_Ulkeler { get; set; }
        public virtual ICollection<DilOkulu_Okullar> DilOkulu_Okullar { get; set; }
    }
}
