//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Okullar
    {
        public DilOkulu_Okullar()
        {
            this.DilOkulu_KonaklamaTipleri = new HashSet<DilOkulu_KonaklamaTipleri>();
            this.DilOkulu_KursTipleri = new HashSet<DilOkulu_KursTipleri>();
            this.DilOkulu_KursTipiKargoHaricler = new HashSet<DilOkulu_KursTipiKargoHaricler>();
        }
    
        public int Id { get; set; }
        public int MerkezId { get; set; }
        public int DilId { get; set; }
        public int UlkeId { get; set; }
        public int SehirId { get; set; }
        public string Baslik { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public string OkulTipi { get; set; }
        public string OkulKapasitesi { get; set; }
        public string SinifKapasitesi { get; set; }
        public string KonaklamaTurleri { get; set; }
        public string OkulOlanaklari { get; set; }
        public string SosyalAktiviteler { get; set; }
        public string SunulanProgramlar { get; set; }
        public string Icerik { get; set; }
        public string Harita { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<bool> OnecikanOkul { get; set; }
        public Nullable<int> GaleriId { get; set; }
        public string Url { get; set; }
        public Nullable<decimal> Ucretler_OkulKayitUcreti { get; set; }
        public Nullable<decimal> Ucretler_KonaklamaAyarlamaUcreti { get; set; }
        public Nullable<decimal> Ucretler_MateryalUcreti { get; set; }
        public string Ucretler_MateryalTahsilatTipi { get; set; }
        public string Ucretler_HavaAlaniKarsilama { get; set; }
        public Nullable<decimal> Ucretler_SaglikSigortasi { get; set; }
        public string Ucretler_SaglikSigortasiTahsilatTipi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
        public Nullable<decimal> Ucretler_KargoUcreti { get; set; }
        public string Ucretler_OkulKayitUcretiArray { get; set; }
        public string Ucretler_KonaklamaAyarlamaUcretiArray { get; set; }
        public string Ucretler_MateryalUcretiArray { get; set; }
        public string Ucretler_SaglikSigortasiArray { get; set; }
        public string Ucretler_OkulKayitEkUcretArray { get; set; }
        public string Ucretler_KonaklamaAyarlamaEkUcretArray { get; set; }
        public string StreetView { get; set; }
        public string PromosyonPdf { get; set; }
        public Nullable<System.DateTime> PromosyonBitisTarihi { get; set; }
    
        public virtual DilOkulu_Diller DilOkulu_Diller { get; set; }
        public virtual ICollection<DilOkulu_KonaklamaTipleri> DilOkulu_KonaklamaTipleri { get; set; }
        public virtual ICollection<DilOkulu_KursTipleri> DilOkulu_KursTipleri { get; set; }
        public virtual DilOkulu_Merkez DilOkulu_Merkez { get; set; }
        public virtual DilOkulu_Sehirler DilOkulu_Sehirler { get; set; }
        public virtual DilOkulu_Ulkeler DilOkulu_Ulkeler { get; set; }
        public virtual ICollection<DilOkulu_KursTipiKargoHaricler> DilOkulu_KursTipiKargoHaricler { get; set; }
    }
}
