//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KursTipiPromosyonTanimlari
    {
        public int Id { get; set; }
        public int KursTipiId { get; set; }
        public byte PromosyonModelId { get; set; }
        public Nullable<int> ExtraHafta_MinimumHafta { get; set; }
        public Nullable<int> ExtraHafta_UcretsizHaftaSayisi { get; set; }
        public Nullable<int> IndirimPromosyonu_Hafta { get; set; }
        public Nullable<int> IndirimPromosyonu_Oran { get; set; }
        public Nullable<int> KursBazli_Hafta { get; set; }
        public Nullable<int> KursBazli_Fiyat { get; set; }
        public Nullable<System.DateTime> PromosyonBitisTarihi { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
        public Nullable<System.DateTime> KursTarihiBaslangic { get; set; }
        public Nullable<System.DateTime> KursTarihiBitis { get; set; }
        public Nullable<int> IndirimPromosyonu_HaftaMax { get; set; }
        public Nullable<int> IndirimPromosyonu_BirimFiyat { get; set; }
    
        public virtual DilOkulu_KursTipleri DilOkulu_KursTipleri { get; set; }
    }
}
