//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Diller
    {
        public DilOkulu_Diller()
        {
            this.DilOkulu_Ulkeler = new HashSet<DilOkulu_Ulkeler>();
            this.DilOkulu_Okullar = new HashSet<DilOkulu_Okullar>();
            this.DilOkulu_KursKategorileri = new HashSet<DilOkulu_KursKategorileri>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public string Url { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public Nullable<byte> Oncelik { get; set; }
    
        public virtual ICollection<DilOkulu_Ulkeler> DilOkulu_Ulkeler { get; set; }
        public virtual ICollection<DilOkulu_Okullar> DilOkulu_Okullar { get; set; }
        public virtual ICollection<DilOkulu_KursKategorileri> DilOkulu_KursKategorileri { get; set; }
    }
}
