//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Merkez
    {
        public DilOkulu_Merkez()
        {
            this.DilOkulu_Okullar = new HashSet<DilOkulu_Okullar>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string GenelBilgi { get; set; }
        public string Logo { get; set; }
        public string Url { get; set; }
        public string OkulSiteLink { get; set; }
        public string FacebookLink { get; set; }
        public string YoutubeLink { get; set; }
        public string TwitterLink { get; set; }
        public string FiyatListesi { get; set; }
        public string Promosyonlar { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int Oncelik { get; set; }
        public byte Durumu { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public string Brosur { get; set; }
        public string Ozet { get; set; }
        public string KurulusTarihi { get; set; }
        public string Akreditasyonlar { get; set; }
    
        public virtual ICollection<DilOkulu_Okullar> DilOkulu_Okullar { get; set; }
    }
}
