//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KursTipiKargoHaricler
    {
        public int Id { get; set; }
        public int OkulId { get; set; }
        public int KursTipiId { get; set; }
    
        public virtual DilOkulu_KursTipleri DilOkulu_KursTipleri { get; set; }
        public virtual DilOkulu_Okullar DilOkulu_Okullar { get; set; }
    }
}
