//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_KursKategorileri
    {
        public DilOkulu_KursKategorileri()
        {
            this.DilOkulu_KursTipleri = new HashSet<DilOkulu_KursTipleri>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public Nullable<int> DilId { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_Diller DilOkulu_Diller { get; set; }
        public virtual ICollection<DilOkulu_KursTipleri> DilOkulu_KursTipleri { get; set; }
    }
}
