//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_VizeRehberi
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public string Icerik { get; set; }
        public string ResimUrl { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public int Oncelik { get; set; }
        public byte Durumu { get; set; }
        public string Url { get; set; }
    }
}
