//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DilOkulu_Ulkeler
    {
        public DilOkulu_Ulkeler()
        {
            this.DilOkulu_Sehirler = new HashSet<DilOkulu_Sehirler>();
            this.DilOkulu_Okullar = new HashSet<DilOkulu_Okullar>();
        }
    
        public int Id { get; set; }
        public int DilId { get; set; }
        public string Baslik { get; set; }
        public string Seo_Keywords { get; set; }
        public string Seo_Descriptions { get; set; }
        public string Aciklama { get; set; }
        public string VizeBilgileri { get; set; }
        public string CalismaIzni { get; set; }
        public string YasamGiderleri { get; set; }
        public string Ulasim { get; set; }
        public string SaglikSistemi { get; set; }
        public string Resim { get; set; }
        public Nullable<int> ParaBirimId { get; set; }
        public Nullable<decimal> VizeUcreti1 { get; set; }
        public Nullable<int> KacAyaKadar1 { get; set; }
        public Nullable<decimal> VizeUcreti2 { get; set; }
        public Nullable<int> KacAyaKadar2 { get; set; }
        public Nullable<decimal> VizeUcreti3 { get; set; }
        public Nullable<int> KacAyaKadar3 { get; set; }
        public byte Oncelik { get; set; }
        public string Url { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public byte Durumu { get; set; }
    
        public virtual DilOkulu_Diller DilOkulu_Diller { get; set; }
        public virtual DilOkulu_ParaBirimleri DilOkulu_ParaBirimleri { get; set; }
        public virtual ICollection<DilOkulu_Sehirler> DilOkulu_Sehirler { get; set; }
        public virtual ICollection<DilOkulu_Okullar> DilOkulu_Okullar { get; set; }
    }
}
